### ISSUE TITLE
Dose it support datetime64?

### ISSUE THREAD

**Issue by doowonee** [suharev7/clickhouse-rs#178]
I use the latest version which is `1.0.0-alpha.1` cause tokio 1.x

Here is the code to use DateTime64
```
        block
            .push(row! {
                time_col: DateTime64(row_data.event_at.timestamp_millis(), (3, UTC))
..........
            })
```

But It crashed like below

```
thread 'main' panicked at 'not implemented', /home/doowonee/.cargo/registry/src/github.com-1ecc6299db9ec823/clickhouse-rs-1.0.0-alpha.1/src/types/column/datetime64.rs:53:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: <clickhouse_rs::types::column::datetime64::DateTime64ColumnData as clickhouse_rs::types::column::column_data::ColumnData>::save
             at /home/doowonee/.cargo/registry/src/github.com-1ecc6299db9ec823/clickhouse-rs-1.0.0-alpha.1/src/types/column/datetime64.rs:53:9
   4: <clickhouse_rs::types::column::chunk::ChunkColumnData as clickhouse_rs::types::column::column_data::ColumnData>::save
             at /home/doowonee/.cargo/registry/src/github.com-1ecc6299db9ec823/clickhouse-rs-1.0.0-alpha.1/src/types/column/chunk.rs:30:9
   5: clickhouse_rs::types::column::Column<K>::write
             at /home/doowonee/.cargo/registry/src/github.com-1ecc6299db9ec823/clickhouse-rs-1.0.0-alpha.1/src/types/column/mod.rs:223:9
   6: clickhouse_rs::types::block::Block<K>::write
             at /home/doowonee/.cargo/registry/src/github.com-1ecc6299db9ec823/clickhouse-rs-1.0.0-alpha.1/src/types/block/mod.rs:365:17
   7: clickhouse_rs::types::block::Block<K>::send_data
```

And I see the source code and It was not implemented yet

```
impl ColumnData for DateTime64ColumnData {
    fn sql_type(&self) -> SqlType {
        let (precision, tz) = self.params;
        SqlType::DateTime(DateTimeType::DateTime64(precision, tz))
    }

    fn save(&self, _encoder: &mut Encoder, _start: usize, _end: usize) {
        unimplemented!()
    }

```

Am I using wrong?

**Comment by caibirdme** [comment]
same issue

**Comment by mplanchard** [comment]
anybody figure this out? I can't figure out how to insert a DateTime64 column

**Comment by suharev7** [comment]
You can see examples of how to insert `DateTime64`  into tests. For example, [here](https://github.com/suharev7/clickhouse-rs/blob/409a4063e11ea380e38e9eb98603d13b306cb994/tests/clickhouse.rs#L2110) or [here](https://github.com/suharev7/clickhouse-rs/blob/409a4063e11ea380e38e9eb98603d13b306cb994/tests/clickhouse.rs#L472).
