### ISSUE TITLE
Insert block of size bigger than INSERT_BLOCK_SIZE

### ISSUE THREAD

**Issue by FlameFactory** [suharev7/clickhouse-rs#204]
I wrote test, I use these connection params: "tcp://default:default@localhost:9000/test?compression=lz4"
```Rust
#[cfg(feature = "tokio_io")]
#[tokio::test]
async fn test_insert_big_block() -> Result<(), Error> {
    let ddl = r"
               CREATE TABLE clickhouse_test_insert_big_block (
               int8  Int8
               ) Engine=Memory";
    let big_block_size = 1024*1024 + 1;

    let block = Block::new()
        .column("int8", vec![-1_i8; big_block_size]);

    let expected = block.clone();
    let pool = Pool::new(database_url());
    let mut c = pool.get_handle().await?;
    c.execute("DROP TABLE IF EXISTS clickhouse_test_insert_big_block")
        .await?;
    c.execute(ddl).await?;
    c.insert("clickhouse_test_insert_big_block", block).await?;
    let actual = c
        .query("SELECT * FROM clickhouse_test_insert_big_block")
        .fetch_all()
        .await?;

    assert_eq!(format!("{:?}", expected.as_ref()), format!("{:?}", &actual));
    Ok(())
}
```
And it fails on line
```
c.insert("clickhouse_test_insert_big_block", block).await?;
```
If you change big_block_size to 1024*1024 the test will pass

CH stacktrace:
```
2023.11.01 11:19:30.477739 [ 267 ] {} <Error> ServerErrorHandler: Code: 99. DB::Exception: Unknown packet 112 from client. (UNKNOWN_PACKET_FROM_CLIENT), Stack trace (when copying this message, always include the lines below):
  
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::TCPHandler::receivePacket() @ 0x147f676a in /usr/bin/clickhouse
2. DB::TCPHandler::readDataNext() @ 0x147f92f8 in /usr/bin/clickhouse
3. DB::TCPHandler::processInsertQuery() @ 0x147f732e in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x147f0792 in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
10. ? @ 0x7f86e3f5e609 in ?
11. __clone @ 0x7f86e3e85293 in ?
 (version 22.1.3.7 (official build))
```

Rust stacktrace:
```
called `Option::unwrap()` on a `None` value
thread 'test_insert_big_block' panicked at clickhouse-rs/src/io/transport.rs:322:15:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x55e737bbff5c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e737bbff5c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e737bbff5c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55e737bbff5c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e737bed63c - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x55e737bed63c - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x55e737bbc91e - std::io::Write::write_fmt::hd8d55fcb462ed7e9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x55e737bbfd44 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55e737bbfd44 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55e737bc1b43 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x55e737bc17df - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:287:9
  11:     0x55e73792c55c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h22dfbb3222a0c5d6
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2021:9
  12:     0x55e73792c55c - test::test_main::{{closure}}::hf2fa6099cd421171
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/test/src/lib.rs:136:21
  13:     0x55e737bc223e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h05249de742e1768e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2021:9
  14:     0x55e737bc223e - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:711:13
  15:     0x55e737bc1f81 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13
  16:     0x55e737bc0486 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  17:     0x55e737bc1d12 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  18:     0x55e73779d6d3 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  19:     0x55e73779d763 - core::panicking::panic::hd907d42d09324a32
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
  20:     0x55e73795f5e7 - core::option::Option<T>::unwrap::h17a92609016c66aa
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/option.rs:935:21
  21:     0x55e737820d9d - clickhouse_rs::io::transport::PacketStream::read_block::{{closure}}::hebdb4c7f7c58e856
                               at src/clickhouse-rs/src/io/transport.rs:322:13
  22:     0x55e7377ce134 - clickhouse_rs::ClientHandle::insert_::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h08627081c2150db5
                               at src/clickhouse-rs/src/lib.rs:485:84
  23:     0x55e7377c6fce - clickhouse_rs::ClientHandle::wrap_future::{{closure}}::he81a5a25b9af0418
                               at src/clickhouse-rs/src/lib.rs:507:17
  24:     0x55e7377cb394 - clickhouse_rs::ClientHandle::insert_::{{closure}}::{{closure}}::hedb426302723a5ea
                               at src/clickhouse-rs/src/lib.rs:489:18
  25:     0x55e7377a3977 - <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll::h8142d9e261b23d08
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/time/timeout.rs:202:33
  26:     0x55e7377d2c72 - clickhouse_rs::with_timeout::{{closure}}::h6e8b6de0e6931719
                               at src/clickhouse-rs/src/lib.rs:607:43
  27:     0x55e7377c9f42 - clickhouse_rs::ClientHandle::insert_::{{closure}}::hf635f39da3b2247d
                               at src/clickhouse-rs/src/lib.rs:493:10
  28:     0x55e7377c830c - clickhouse_rs::ClientHandle::insert::{{closure}}::h42cee275bad1a6c3
                               at src/clickhouse-rs/src/lib.rs:440:61
  29:     0x55e73786c60c - clickhouse::test_insert_big_block::{{closure}}::h4a8e8739be33c7e6
                               at src/clickhouse-rs/tests/clickhouse.rs:275:57
  30:     0x55e73784836d - <core::pin::Pin<P> as core::future::future::Future>::poll::hd82c22814433e0d0
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/future/future.rs:125:9
  31:     0x55e73784824a - <core::pin::Pin<P> as core::future::future::Future>::poll::h5a8e4bb9907ad1dd
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/future/future.rs:125:9
  32:     0x55e73782d603 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}::h46ec9de3dde89f23
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/current_thread/mod.rs:665:57
  33:     0x55e73782d0df - tokio::runtime::coop::with_budget::he725dd076f63a1e2
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/coop.rs:107:5
  34:     0x55e73782d0df - tokio::runtime::coop::budget::h80ed4668b8a461f2
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/coop.rs:73:5
  35:     0x55e73782d0df - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::h4ec4f28723cc682a
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/current_thread/mod.rs:665:25
  36:     0x55e737828d8d - tokio::runtime::scheduler::current_thread::Context::enter::h589ae1bdd918c213
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/current_thread/mod.rs:410:19
  37:     0x55e73782b0b7 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::h143b2d1b32a780f1
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/current_thread/mod.rs:664:36
  38:     0x55e73782ac42 - tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}::h64349f1b178c3521
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/current_thread/mod.rs:743:68
  39:     0x55e7378645da - tokio::runtime::context::scoped::Scoped<T>::set::hed024f6de6b63c10
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/context/scoped.rs:40:9
  40:     0x55e73782d78a - tokio::runtime::context::set_scheduler::{{closure}}::h2f230b4a4e875e2f
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/context.rs:176:26
  41:     0x55e7377d4f9e - std::thread::local::LocalKey<T>::try_with::ha929f5070005b646
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:270:16
  42:     0x55e7377d385c - std::thread::local::LocalKey<T>::with::h7f62fe11e09fd31c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:246:9
  43:     0x55e73782d6a1 - tokio::runtime::context::set_scheduler::h631bd839e4dc69c7
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/context.rs:176:9
  44:     0x55e73782a8de - tokio::runtime::scheduler::current_thread::CoreGuard::enter::he59dc1130aaf6ff3
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/current_thread/mod.rs:743:27
  45:     0x55e73782ad92 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::hd397b56b83906ecd
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/current_thread/mod.rs:652:19
  46:     0x55e73782768f - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}::h2edb4c885b7885f5
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  47:     0x55e7378ee59e - tokio::runtime::context::runtime::enter_runtime::hdc882c521f213595
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/context/runtime.rs:65:16
  48:     0x55e737827038 - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::h8599829a0f0757b4
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  49:     0x55e737862d3a - tokio::runtime::runtime::Runtime::block_on::h5ec0861ec3823c39
                               at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/runtime.rs:348:47
  50:     0x55e7377a6103 - clickhouse::test_insert_big_block::h1d36bc58db3fac8d
                               at src/clickhouse-rs/tests/clickhouse.rs:282:5
  51:     0x55e73786b91d - clickhouse::test_insert_big_block::{{closure}}::h6b791d0ae73e9054
                               at src/clickhouse-rs/tests/clickhouse.rs:259:37
  52:     0x55e73784e326 - core::ops::function::FnOnce::call_once::h180616b6dc1a9402
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  53:     0x55e7379315ef - core::ops::function::FnOnce::call_once::he2e7294d6e0366fc
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  54:     0x55e7379315ef - test::__rust_begin_short_backtrace::h13549e99f98e3254
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/test/src/lib.rs:626:18
  55:     0x55e73793067e - test::run_test_in_process::{{closure}}::h9c2c3d1665ffe092
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/test/src/lib.rs:649:60
  56:     0x55e73793067e - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hec1896877d3d50ca
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9
  57:     0x55e73793067e - std::panicking::try::do_call::hc7aed7412be3e0dc
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  58:     0x55e73793067e - std::panicking::try::h011fbc524cd7e3ba
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  59:     0x55e73793067e - std::panic::catch_unwind::hff05d0891bc5bb82
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  60:     0x55e73793067e - test::run_test_in_process::h87f0657a1c0aaab4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/test/src/lib.rs:649:27
  61:     0x55e73793067e - test::run_test::{{closure}}::hc4dd34f501797e16
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/test/src/lib.rs:572:43
  62:     0x55e7378f7fd3 - test::run_test::{{closure}}::h1201d47565297bcc
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/test/src/lib.rs:600:41
  63:     0x55e7378f7fd3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6de9d5784bb58c62
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:154:18
  64:     0x55e7378fdbeb - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h0a3dd4432bd9a04d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/mod.rs:529:17
  65:     0x55e7378fdbeb - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h05af39418a9230d5
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9
  66:     0x55e7378fdbeb - std::panicking::try::do_call::h6f430b03009d827b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  67:     0x55e7378fdbeb - std::panicking::try::h3275ae04389ad69a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  68:     0x55e7378fdbeb - std::panic::catch_unwind::h77f388467ce5722e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  69:     0x55e7378fdbeb - std::thread::Builder::spawn_unchecked_::{{closure}}::h308964f897d35a6e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/mod.rs:528:30
  70:     0x55e7378fdbeb - core::ops::function::FnOnce::call_once{{vtable.shim}}::h98d901cf00b6c865
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  71:     0x55e737bc6b05 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::haadd4e5af2ab0d62
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  72:     0x55e737bc6b05 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he4ba1fb09c16d807
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  73:     0x55e737bc6b05 - std::sys::unix::thread::Thread::new::thread_start::he524ecf4b47bee95
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/unix/thread.rs:108:17
  74:     0x7f339c694ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  75:     0x7f339c726a40 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  76:                0x0 - <unknown>

error: test failed, to rerun pass `-p clickhouse-rs --test clickhouse`
error: 1 target failed:
    `-p clickhouse-rs --test clickhouse`
```

**Comment by suharev7** [comment]
Thanks for discovering this bug and writing a test to reproduce it. [Here](https://github.com/suharev7/clickhouse-rs/commit/b1f627b6acf4d40bd1ce4a975c826f6b11b76088) is the commit with the edit.

**Comment by FlameFactory** [comment]
Awesome, thanks for fixing it!
UPD: cargo fmt shows diffs now in test_insert_big_block
